# Generated by Django 6.0 on 2026-02-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre / Cohorte')),
                ('date', models.DateField(verbose_name='Fecha de inicio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('features', models.TextField(blank=True, verbose_name='Características y condiciones')),
                ('advisor_id', models.IntegerField(blank=True, null=True, verbose_name='ID Asesor (Agon)')),
                ('advisor_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre Asesor (cache)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo / Cohorte',
                'verbose_name_plural': 'Grupos / Cohortes',
                'ordering': ['-date'],
            },
        ),
    ]
