# Generated by Django 6.0 on 2026-02-21 06:08

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('type', models.CharField(choices=[('Acta Estudiantes', 'Acta Estudiantes'), ('Informe', 'Informe'), ('Memorando', 'Memorando'), ('Otro', 'Otro')], default='Informe', max_length=50)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('purpose', models.TextField(verbose_name='Propósito del documento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Acta Estudiantes', 'Acta Estudiantes'), ('Informe', 'Informe'), ('Memorando', 'Memorando'), ('Otro', 'Otro')], default='Acta Estudiantes', max_length=50)),
                ('advisor_id', models.IntegerField(blank=True, null=True, verbose_name='ID Docente (Agon)')),
                ('advisor_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre Docente (cache)')),
                ('date', models.DateField(verbose_name='Fecha del acta')),
                ('logros', models.TextField(blank=True, verbose_name='Logros')),
                ('acuerdos', models.TextField(blank=True, verbose_name='Acuerdos')),
                ('sintesis', models.TextField(blank=True, verbose_name='Compromisos / Síntesis')),
                ('pdf', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pdf')),
                ('photo1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo1')),
                ('photo2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas', to='grupos.grupo', verbose_name='Cohorte')),
                ('linked_doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas', to='actas.documento', verbose_name='Documento base')),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': 'Actas',
                'ordering': ['-date'],
            },
        ),
    ]
