# Generated by Django 6.0 on 2026-02-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='ACTA', max_length=20)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('total', models.CharField(blank=True, max_length=20)),
                ('fecha', models.CharField(blank=True, max_length=30)),
                ('hora_inicio', models.CharField(blank=True, max_length=20)),
                ('hora_final', models.CharField(blank=True, max_length=20)),
                ('instancias', models.TextField(blank=True)),
                ('lugar', models.TextField(blank=True)),
                ('orden_dia', models.TextField(blank=True)),
                ('desarrollo', models.TextField(blank=True)),
                ('proxima_convocatoria', models.TextField(blank=True, default='N/A')),
                ('anexos', models.TextField(blank=True, default='N/A')),
                ('asistentes', models.JSONField(blank=True, default=list)),
                ('ausentes', models.JSONField(blank=True, default=list)),
                ('invitados', models.JSONField(blank=True, default=list)),
                ('compromisos', models.JSONField(blank=True, default=list)),
                ('firmas', models.JSONField(blank=True, default=list)),
                ('comentarios', models.JSONField(blank=True, default=list)),
                ('participantes_ids', models.JSONField(blank=True, default=list, help_text='Lista de user_id de AGON de todos los involucrados')),
                ('creador_id', models.IntegerField(blank=True, null=True)),
                ('creador_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acta de Reunión',
                'verbose_name_plural': 'Actas de Reunión',
                'ordering': ['-created_at'],
            },
        ),
    ]
