# Generated by Django 6.0 on 2026-02-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0002_actareunion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actareunion',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='anexos',
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='asistentes',
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='ausentes',
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='compromisos',
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='creador_name',
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='desarrollo',
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='firmas',
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='hora_final',
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='instancias',
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='invitados',
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='orden_dia',
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='proxima_convocatoria',
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='actareunion',
            name='total',
        ),
        migrations.AddField(
            model_name='actareunion',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='actareunion',
            name='participantes_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
