# Generated by Django 6.0 on 2026-02-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0003_simplify_actareunion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('firma_data', models.TextField(help_text='Base64 de la imagen de firma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firma de Usuario',
            },
        ),
    ]
