# Generated by Django 6.0 on 2026-03-08 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('creador_id', models.IntegerField(verbose_name='ID Docente (Agon)')),
                ('cant_evaluadores', models.IntegerField(default=1, verbose_name='Cantidad de evaluadores')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='grupos.grupo')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='evaluaciones.rubrica')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('orden', models.IntegerField(default=0)),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='evaluaciones.rubrica')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluador_id', models.IntegerField(verbose_name='ID Evaluador (Agon)')),
                ('estudiante_id', models.IntegerField(verbose_name='ID Estudiante (Agon)')),
                ('puntajes', models.JSONField(default=dict, help_text="{'criterio_id': nota_1_a_5}")),
                ('nota_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('comentarios', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluacion_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='evaluaciones.evaluaciongrupo')),
            ],
            options={
                'unique_together': {('evaluacion_grupo', 'evaluador_id', 'estudiante_id')},
            },
        ),
    ]
