# Generated by Django 6.0 on 2026-03-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='estudiante_id',
            new_name='usuario_agon_id',
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('evaluacion_grupo', 'usuario_agon_id')},
        ),
        migrations.RemoveField(
            model_name='evaluaciongrupo',
            name='grupo',
        ),
        migrations.AddField(
            model_name='evaluaciongrupo',
            name='grupo_agon_id',
            field=models.IntegerField(default=0, verbose_name='ID Clase/Grupo en AGON'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluaciongrupo',
            name='grupo_nombre',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del grupo (cache)'),
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='evaluador_id',
        ),
    ]
