# Generated by Django 6.0 on 2026-03-09 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_use_grupo_agon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='puntajes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='criterio',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre del criterio'),
        ),
        migrations.CreateModel(
            name='NivelCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(verbose_name='Valor numérico del nivel')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del nivel de logro')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='evaluaciones.criterio')),
            ],
            options={
                'ordering': ['valor'],
                'unique_together': {('criterio', 'valor')},
            },
        ),
    ]
