# Generated by Django 6.0 on 2026-03-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_add_nivelcriterio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='evaluador_id',
            field=models.IntegerField(default=0, help_text='ID del docente o invitado que registró esta calificación', verbose_name='ID Evaluador (Agon)'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('evaluacion_grupo', 'usuario_agon_id', 'evaluador_id')},
        ),
    ]
