# Generated by Django 6.0 on 2026-03-11 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluaciones', '0004_add_evaluador_id_to_calificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del espacio')),
                ('semestre', models.CharField(default='', max_length=20, verbose_name='Semestre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('objetivos', models.TextField(blank=True, verbose_name='Objetivos de aprendizaje')),
                ('profesor_id', models.IntegerField(verbose_name='ID Docente (AGON)')),
                ('grupos_agon_ids', models.JSONField(default=list)),
                ('grupos_nombres', models.JSONField(default=list, verbose_name='Nombres cache')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='Color')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entorno Académico',
                'verbose_name_plural': 'Entornos Académicos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del corte')),
                ('numero', models.IntegerField(default=1)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=33.33, max_digits=5, verbose_name='% de la nota final')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('entorno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes', to='entornos.entorno')),
            ],
            options={
                'verbose_name': 'Corte',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('rubrica', 'Por Rúbrica'), ('manual', 'Nota Manual')], default='rubrica', max_length=10)),
                ('peso', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Peso dentro del corte (%)')),
                ('nota_max', models.DecimalField(decimal_places=1, default=5.0, max_digits=4)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='entornos.corte')),
                ('rubrica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregables', to='evaluaciones.rubrica')),
            ],
            options={
                'verbose_name': 'Entregable',
                'ordering': ['orden', 'fecha_entrega'],
            },
        ),
    ]
